baseURL: "https://aryasuneesh.github.io/" 
title: Arya Suneesh
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Experience
          url: experience/
          weight: 1 
        - name: Projects
          url: projects/
          weight: 2
        - name: Research
          url: research/
          weight: 3
        - name: Publications
          url: publications/
          weight: 4 
        - name: Blog
          url: blog/
          weight: 5

params:
    description: "Arya Suneesh's personal website showcasing her journey as an NLP Engineer, AI researcher, and quantum computing enthusiast. Explore her professional experience, research projects, and technical achievements."
    author: Arya Suneesh
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["experience","projects","research","publications","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Arya Suneesh
          subtitle: "NLP Engineer at TIFIN RM with expertise in AI research and quantum computing. Undergraduate of IIIT Kottayam with international research experience."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            # - name: Experience
            #   url: experience/
            - name: Resume
              url: Arya_Suneesh_Resume_Website.pdf
            - name: Projects
              url: projects/
            - name: Research
              url: research/
            - name: Publications
              url: publications/
            - name: Blog
              url: blog/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/

    socialIcons:
        - name: CV
          url: Arya_Suneesh_Resume_Website.pdf
        - name: Email
          url: mailto:aryasuneesh3@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/arya-suneesh/
        - name: GitHub
          url: https://github.com/aryasuneesh
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=0tq3v-4AAAAJ&hl=en
        - name: Twitter
          url: https://x.com/arya_suneesh
        - name: YouTube
          url: https://www.youtube.com/@aryasuneesh/
        - name: Substack
          url: https://aryasuneesh.substack.com

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Arya Suneesh"
      icon: icons8-flower-16.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2